WRF/WPS configure still want to use icc, which is gone and replaced with icx.
ungrib still does not compile without code modifications:

mpicc -D_UNDERSCORE -DBYTESWAP -DLINUX -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -DBIT32 -D_MPI -D_UNGRIB -w -c cio.c
cio.c:52:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
c_open(unit, nunit, name, mode, err, oflag)
^
int
cio.c:24:16: note: expanded from macro 'c_open'
#define c_open c_open_
               ^
cio.c:117:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
bn_seek(fd, bread, mode, iprint)
^
int
cio.c:27:17: note: expanded from macro 'bn_seek'
#define bn_seek bn_seek_
                ^
cio.c:155:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
bn_read(fd, buf, nbuf, bread, ios, idiag)
^
int
cio.c:26:17: note: expanded from macro 'bn_read'
#define bn_read bn_read_
                ^
cio.c:201:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
bnwrit_(fd, buf, nbuf, bwritten, err, idiag)
^
int
cio.c:235:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
c_close(nunit, iprint, err)
^
int
cio.c:25:17: note: expanded from macro 'c_close'
#define c_close c_close_
                ^
5 errors generated.
make[1]: [Makefile:96: cio.o] Error 1 (ignored)