Feature/40 build wrf container (#72)
* Created a docker container that was successfully tested on redcloud with 120 processes on a single node.

* Trimmed down the number of intel-oneapi packages that get installed to reduce the size of the image.

* Successfully built WRF v4.5.1.

* Updated the Dockerfile to be a multi-stage build.  In the second stage, we copy over compiled libaries and applications, and only install the intel runtime packages so that we can redistribute the code (i.e., omits Intel compilers).  Size is also down considerably from 8 GB to 3 GB.

* Updated to the latest WRF version and removed the intel classic compilers.

* Removed an unnecessary and missing library.

* ignore libs directory.

* WRF/WPS configure still want to use icc, which is gone and replaced with icx.

ungrib still does not compile without code modifications:

mpicc -D_UNDERSCORE -DBYTESWAP -DLINUX -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -DBIT32 -D_MPI -D_UNGRIB -w -c cio.c
cio.c:52:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
c_open(unit, nunit, name, mode, err, oflag)
^
int
cio.c:24:16: note: expanded from macro 'c_open'
#define c_open c_open_
               ^
cio.c:117:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
bn_seek(fd, bread, mode, iprint)
^
int
cio.c:27:17: note: expanded from macro 'bn_seek'
#define bn_seek bn_seek_
                ^
cio.c:155:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
bn_read(fd, buf, nbuf, bread, ios, idiag)
^
int
cio.c:26:17: note: expanded from macro 'bn_read'
#define bn_read bn_read_
                ^
cio.c:201:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
bnwrit_(fd, buf, nbuf, bwritten, err, idiag)
^
int
cio.c:235:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
c_close(nunit, iprint, err)
^
int
cio.c:25:17: note: expanded from macro 'c_close'
#define c_close c_close_
                ^
5 errors generated.
make[1]: [Makefile:96: cio.o] Error 1 (ignored)

* Some of the runtime WRF/WPS scripts require CSH.

* Created a patch file to fix syntax issues in ungrib/src/cio.c to follow ISO C99 syntax rules to allow base compilation with icx with no flags disabling warnings/errors.

Updated the build_wrf.sh script to include functions to check the build status of each component and exit if something fails.

* Fixed exit code

* Problem with sourcing /etc/bash.bashrc file. Moved back to /etc/bashrc.

* Switched to development version of WPS, which does not need the patch we created.
Changing files to be owned by root for apptainer purposes.
WRF needs to run the compile step twice to build everything successfully.

* iwrf-lulc build files.

* Updated the version of WPS from develop to 4.6.0

---------

Co-authored-by: George McCabe <23407799+georgemccabe@users.noreply.github.com>